package model;

// Generated Sep 21, 2013 12:37:55 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "database1")
public class Role implements java.io.Serializable {

	private String roleName;
	private Set<Accountrole> accountroles = new HashSet<Accountrole>(0);

	public Role() {
	}

	public Role(String roleName) {
		this.roleName = roleName;
	}

	public Role(String roleName, Set<Accountrole> accountroles) {
		this.roleName = roleName;
		this.accountroles = accountroles;
	}

	@Id
	@Column(name = "RoleName", unique = true, nullable = false, length = 20)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Accountrole> getAccountroles() {
		return this.accountroles;
	}

	public void setAccountroles(Set<Accountrole> accountroles) {
		this.accountroles = accountroles;
	}

}
