package model;

// Generated Sep 9, 2013 12:20:02 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private String roleName;
	private Set<Accountrole> accountroles = new HashSet<Accountrole>(0);

	public Role() {
	}

	public Role(String roleName) {
		this.roleName = roleName;
	}

	public Role(String roleName, Set<Accountrole> accountroles) {
		this.roleName = roleName;
		this.accountroles = accountroles;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set<Accountrole> getAccountroles() {
		return this.accountroles;
	}

	public void setAccountroles(Set<Accountrole> accountroles) {
		this.accountroles = accountroles;
	}

}
